Wallet/Screens/Homescreen/WalletHomescreenViewController.swift

By initializing views after setting the state-observer, the views are initialized correctly.

fixes flickering of homescreen on wallet start

---

Verifier/Logic/AppDelegate.swift
Wallet/Logic/AppDelegate.swift

Adds blur view when application goes to background and removes blur view when app becomes active. 
iOS is taking a screenshot when the app goes into background. This is where a blurview is added, so that the information in this screenshot is blurred. When the app is used again, this blurred view will be smoothly animated removed.

adds blur view when application resigns

---

CovidCertificate.xcodeproj/project.pbxproj
CovidCertificate.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
CovidCertificate/SharedLogic/Helpers/UBLocalized+CC.swift
Translations/Strings+Generated.swift
Translations/UBTemplate.stencil
Wallet/Screens/Certificates/CertificateAddDetailView.swift
Wallet/Screens/Certificates/CertificateDetailView.swift
Wallet/Screens/Certificates/CertificateDetailViewController.swift
swiftgen.yml

- changes swiftgen translation UBTemplate.stencil to give accses to the keys to simplify getting translations
- adds English description labels to the certificate detail when English is not the phone language anyway

Feature: Add English labels

---

CovidCertificate.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
CovidCertificate/SharedLogic/Verifier/Verifier.swift
Verifier/Logic/Error/VerifierErrors+CC.swift
Wallet/Logic/Error/WalletErrors+CC.swift
Wallet/Screens/Certificates/CertificateTableViewCell.swift

- updates SDK to include invalid type error when format of certificate invalid (e.g. multiple 
- adds correct error message on wallet / verifier to show error invalid format

adds additional error state for certificates with invalid format

---

CovidCertificate/SharedLogic/Verifier/Verifier.swift

- Only show error codes for national rules on the Wallet app by not propagating the error code from the SDK. In this way, the verifier app never shows information about the type of certificate like "not recognized test type" or some kind of "vaccination error".

Error display: No national rules errors displayed on Verifier

---

CovidCertificate/SharedUI/Helpers/UIView+CC.swift
Wallet/Screens/Certificates/CertificateStateValidityView.swift
Wallet/Screens/Certificates/CertificateStateView.swift

- hides validity and error view in the loading state of certificate detail

Hide validity information in certificate detail refresh

---

Wallet/Logic/AppDelegate.swift

This PR makes sure we don't perform any requests until the user completed onboarding.

Make sure refreshing of trust list does not happen until onboarding is complete

---

CovidCertificate.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

C.f. https://github.com/admin-ch/CovidCertificate-SDK-iOS/pull/38

Update SDK to include Storage deserializing bug

---

CovidCertificate.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

This pull-request updates the SDK to improve offline-mode handling. See https://github.com/admin-ch/CovidCertificate-SDK-iOS/pull/45 for details.

Update SDK to improve offline mode

---

Wallet/Logic/ImportHandler/ImportHandler.swift

Opening the PDF from an app that provides a security-scoped URL (e.g. the Files App with a file on iCloud Drive) requires a call startAccessingSecurityScopedResource to provide access to the resource.

Access security-scoped PDF resource

---

CovidCertificateTests/LuhnTests.swift
Wallet/Logic/Crypto/Luhn.swift

We adjust the Luhn-Alphabet to remove the "G" character. Further, we harden check sum checks to first check for invalid characters before calculating the checksum. Also we remove the force unwrap in favour of the null coalescing operator to just return something (but not crash). 
To test cross-platform compatibility we add Luhn-Codes generated and verified by the Android code. Further we introduce test cases with codes which have one permutation in it, to verify the failing. 
Last but not least an error code with bogus character is checked to ensure graceful handling.

Fix luhn alphabet

---

Verifier/Logic/AppDelegate.swift

This pull-request makes sure last scanned certificate is discarded and app is reset to homescreen when the app goes to background (ready to scan new certificates)

Reset verifier to home screen when put into background

---

CovidCertificate/Supporting Files/Wallet-Info.plist
Wallet/Logic/ImportHandler/ImportHandler.swift

Adds handling for a custom URL-scheme. This allows other apps to transfer a certificate QR code to the wallet app.
Currently, the scheme covidcert and hcert are supported. A certificate QR code can be opened in the wallet app by creating the URL in the following format chcovidcert://URL-ENCODED(QR-Code-String)

Custom URL scheme

---

CovidCertificate.xcodeproj/project.pbxproj
CovidCertificate.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
CovidCertificate/SharedLogic/Networking/Base/URLSession+pinning.swift
CovidCertificate/SharedUI/Base/HomescreenBaseViewController.swift
CovidCertificate/SharedUI/Screens/Debug/DebugSwitchView.swift
CovidCertificate/SharedUI/Screens/Debug/DebugView.swift
CovidCertificate/SharedUI/Screens/Debug/DebugViewController.swift
Wallet/Logic/AppDelegate.swift

This PR adds a DebugViewController to DEV and DEBUG builds. It is accessible by double-tapping on the bund icon. Currently, only certificate pinning can be disabled.

Adds a DebugViewcontroller

---

Wallet/Logic/TransferCode/InAppDelivery.swift

With the get action the certificate doesn't get deleted by the backend

Use correct singature action for complete request

---

CovidCertificate/Supporting Files/Wallet-Info.plist

This hides the app from the File application. It was initially added due to an Appstore Connect warning (ITMS-90737).

Bugfix: Make sure Covid Certificate container is not visible in "Files" app

---

Wallet/Screens/Homescreen/HomescreenBottomView.swift
Wallet/Screens/Homescreen/HomescreenOnboardingViewController.swift
Wallet/Screens/Homescreen/WalletHomescreenViewController.swift

This PR fixes the homescreen layout for small phones by putting the content below the FAQ-button and making it scrollable until it is completely above the FAQ-button.

Fix homescreen layout for small phones

---

CovidCertificate/Supporting Files/Wallet-Info.plist

As suggested by `ITMS-90737` we're adding `LSSupportsOpeningDocumentsInPlace` and setting it to false

Set LSSupportsOpeningDocumentsInPlace to false

---

CovidCertificate.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

Update SDK to latest version which contains https://github.com/admin-ch/CovidCertificate-SDK-iOS/pull/53

Update SDK to latest version

---

CovidCertificate/SharedUI/Views/CertificateLightExpirationTimer.swift

- set CertificateLightExpirationTimer height required

Bugfix: expiration timer on small devices

---

CovidCertificate/SharedLogic/Verifier/Verifier.swift

- consider skipped verification state as success
- this fixes a bug in the [verifier.swift](https://github.com/admin-ch/CovidCertificate-App-iOS/blob/main/CovidCertificate/SharedLogic/Verifier/Verifier.swift#L192) where all verification states are checked if they are successful

Bugfix: consider skipped verification state as success

---

CovidCertificate.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
CovidCertificate/SharedLogic/Helpers/EuHealthCert+CC.swift
CovidCertificate/SharedUI/Views/QRCodeNameView.swift
Verifier/Screens/Check/VerifyCheckContentViewController.swift
Wallet/Screens/Certificates/CertificateAddDetailView.swift

This PR moves the dob parsing from the app to the SDK (also see https://github.com/admin-ch/CovidCertificate-SDK-iOS/pull/60)

Move date-of-birth ("dob") from app to SDK

---

Wallet/Logic/ImportHandler/ImportHandler.swift

certificates are normally on the first page. 
Only look at the first 5 pages, this resolves a memory issue when a user tries to import a huge pdf.

Only look at first 5 pages of pdf

---

CovidCertificate.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Wallet/Screens/Certificates/CertificateDetailViewController.swift

- Lightcertificates can only be created for certificates that have a valid state and were issued by Switzerland
- PDF export is enabled for certificates that were issued by Switzerland and have a valid signature

Bugfix: Lightcertificate and PDF-export only for certificates issued by Switzerland

---

Wallet/Screens/Certificates/WalletDetailViewController.swift

This resolves an issue where a certificate doesn't get deleted after the certificate light was disabled

Bugfix: propagate certificate to certificateDetailVC

---

CovidCertificate/Supporting Files/Impressum/de/impressum.html
CovidCertificate/Supporting Files/Impressum/en/impressum.html
CovidCertificate/Supporting Files/Impressum/fr/impressum.html
CovidCertificate/Supporting Files/Impressum/it/impressum.html
CovidCertificate/Supporting Files/Impressum/rm/impressum.html

The imprint license `h1` is actually a link, therefor the role has to be set to none.

Minor accessbility fixes

---

CovidCertificate.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Wallet/Logic/User/UserCertificate.swift
Wallet/Logic/User/WalletUserStorage.swift
Wallet/Screens/TransferCode/TransferCodeDetailViewController.swift

Currently, a new created transfer code overwrites the existing one

Bufix: Allow multiple transfer codes

---

Wallet/Screens/Homescreen/HomescreenCertificatesViewController.swift

The return in the guard prevented further verifier checks from being executed on the homescreen.

Fixes certificate check after expired transfer code

---

Wallet/Logic/User/UserCertificate.swift
Wallet/Logic/User/WalletUserStorage.swift
Wallet/Screens/Certificates/CertificateAddDetailView.swift

Fixes an issue in certificate comparison introduced with https://github.com/admin-ch/CovidCertificate-App-iOS/pull/145.
The whole Usercertificate object has to be compared in order for the observer to be triggered.

Fixes issues in certificate comparison

---

Wallet/Logic/AppDelegate.swift
Wallet/Logic/ImportHandler/ImportHandler.swift

delete PDFs on the filesystem. A PDF can be saved there without being encrypted in two cases:
1. when the app gets killed while sharing
2. the OS stores the PDF in an inbox folder when importing it
Therefore we delete all PDFs on the app start to be sure.

Delete all unencrypted PDFs on app start

---

CovidCertificate.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Verifier/Screens/Check/VerifyCheckContentViewController.swift

Differentiate the success text for light certificates and normal certificates in the verification app

Verifier light certificate text

---

CovidCertificate/SharedUI/Views/IconImageRowView.swift

In the disabled state, remove the arrow as designed. It's clearer that you cannot click the disabled buttons.

Remove arrow in IconImageRow

---

Translations/Strings+Generated.swift
Translations/de.lproj/Localizable.strings
Translations/en.lproj/Localizable.strings
Translations/fr.lproj/Localizable.strings
Translations/it.lproj/Localizable.strings
Translations/rm.lproj/Localizable.strings
Wallet/Screens/Certificates/CertificateDetailView.swift

In english, the user gets the information about the date format used in the app. It's either part of the label in english (if the app is used in english) and it's part of the english label if the translated labels are shown.

Adds date format information to certificate

---

Wallet/Logic/AppDelegate.swift

On app-start we delete all PDFs in the `temporaryDirectory` and `documentDirectory` for security reasons. This had the side-effect that currently is not possible to import a PDF when the app was not running previously. Now all PDFs get deleted but the one passed in the launch options.

Fixes coldstart PDF import

---

Wallet/Screens/Certificates/CertificateAddDetailView.swift
Wallet/Screens/Certificates/CertificateDetailView.swift
Wallet/Screens/Certificates/CertificateDetailViewController.swift

VoiceOver in ceertificate detail: 
- Does not read english labels anymore (in all non-english languages)
- Fixes problems with wrong labels being spoken
- Focuses state view after refresh
QR-Code scanning:
- After scanning it is also spoken that a QR-code is there

Accessibility bugfixes

---

Verifier/Logic/AppDelegate.swift
Verifier/Screens/Check/VerifyCheckViewController.swift
Verifier/Screens/Check/VerifyViewController.swift

https://github.com/admin-ch/CovidCertificate-App-iOS/issues/169
This would be a solution to scan faster after going to a different app. If the user is already scanning, we just dismiss the last visible result.

Faster scanning after going to background

---

CovidCertificate/SharedLogic/Helpers/EuHealthCert+CC.swift
Wallet/Screens/Certificates/CertificateDetailViewController.swift

Previously all exported certificates were named equally this cause some confusion. This PR makes the exported filename unique. 
The PDF are now named "covid-certificate-{last name}-{first name}-{last 4 characters of uvci}.pdf"

Make certificate pdf export name unique

---

Wallet/Logic/AppDelegate.swift
Wallet/Screens/TransferCode/TransferCodeViewController.swift

When going in background, dismiss the generated transfer code view (last step in transfer code generation), so that the next time the user enters the app, the user sees the homescreen and therefore eventually the downloaded certificate.

Dismiss generated Transfer Code

---

CovidCertificate/SharedUI/Base/HomescreenBaseViewController.swift
CovidCertificate/SharedUI/Views/PopUpView.swift
Wallet/Screens/Homescreen/WalletHomescreenViewController.swift

This PR fixes problems on the Wallet homescreen when VoiceOver is turned on. By showing the PopupView with accessibilityViewIsModal, these problems are fixed.
- Fixes problem that FAQ-button can be reached when action view to add certificate is shown
- Fixes problem that homescreen can be reached when InfoBox/Push-Popup is presented

Fixes problems with view hierarchy on Wallet homescreen with VoiceOver

---

Wallet/Logic/AppDelegate.swift
Wallet/Logic/User/SecureStorage/Enclave.swift

We already delete all keychain items of the type `kSecClassGenericPassword`. This PR deletes items of tye `kSecClassKey` on app start. This allows for a testable update simulation.

Delete all keychain keys on first app start

---

CovidCertificate/SharedUI/Style/LabelType.swift
Wallet/Screens/Certificates/SmallTransferCodeLabel.swift

Uses also Fira Bold in list view for transfer code.

Use correct font in certificates list view

---

CovidCertificate/SharedLogic/Helpers/EuHealthCert+CC.swift

This PR changes the display logic of names both in the wallet and in the verifier app. Whenever the normal names (`fn`, `gn`) are null or empty, the standardized names (`fnt`, `gnt`) are used instead.

Use standardized names (fnt, gnt) as fallback when names (fn, gn) are not available

---

CovidCertificate.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Wallet/Screens/Certificates/CertificateDetailView.swift

This pull-request makes sure we show the new antibody-recovery certificate as "Recovery" (and not test).

Add display logic for serological test

---

CovidCertificate/Resources/Config/config_wallet.json

This pull-request makes sure we start with timeshiftDetectionEnabled = false directly after initial installation. Will be enabled after the first config update (if enabled on backend).

Start with "timeshiftDetectionEnabled" = false in pre-bundled config

---

Wallet/Screens/Certificates/CertificateDetailView.swift
Wallet/Screens/Certificates/CertificateDetailViewController.swift
Wallet/Screens/Certificates/CertificateQRCodeStateView.swift
Wallet/Screens/Certificates/CertificateStateView.swift

This PR fixes some state problems that could occur in the certificate detail view, when multiple check operations were running simultaneously (e.g. when the user opened a certificate while a check operation on the homescreen was still in progress, and then pressed the refresh button).
Furthermore, many UI update calls are reduced to the minimum by only calling them when the state has actually changed. This also fixes a UI bug where the refresh rotate animation would stop before the refresh was actually done.

Certificate detail state problems

---

CovidCertificate.xcodeproj/project.pbxproj
CovidCertificate.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
CovidCertificate/SharedLogic/Verifier/Verifier.swift
Wallet/Screens/Certificates/CertificateAddDetailView.swift
Wallet/Screens/Certificates/CertificateDetailView.swift
Wallet/Screens/Certificates/CertificateDetailViewController.swift

In the last release, a flag called `isSwitzerlandOnly` was introduced in the SDK that exposed whether a specific certificate was only valid in Switzerland. This flag is used to display additional information to the user in the wallet app. The rules of whether to show this flag were hardcoded in the SDK, so far returning true for light certificates and serological tests.
This PR changes the behaviour so that the `isSwitzerlandOnly` flag is now computed with the display rules, which makes it more flexible since the rules can be updated from the backend.

Use isSwitzerlandOnly flag from display rules

---

Wallet/Screens/Certificates/SmallTransferCodeLabel.swift
Wallet/Screens/Homescreen/HomescreenCertificateView.swift

This PR fixes two issues with transfer codes:
- When a transfer code expires, on the homescreen the app would still show a "waiting" state (wrong title and icon). Now the state is consistent with what is shown in the detail screen.
- When a transfer code is failed or expired, the state is now shown in the correct font in the list view.

Transfercode states

---

CovidCertificate.xcodeproj/project.pbxproj
CovidCertificate.xcodeproj/xcshareddata/xcschemes/Translation.xcscheme
iosTranslation.json

This PR extends the PATH environment variable to include the default homebrew install directory for both Intel and Apple Silicon Macs. The following executables should now correctly be picked up by Xcode:
- iOSTranslations (to download Translations from POEditor)
- swiftgen (to generate the typed strings enum)
- swiftformat (to automatically format swift files when building with the DEBUG configuration)

Fix translation fetching, string generating and swiftformat for M1 macs

---

CovidCertificate/SharedUI/Views/QRScanner/NSQRScanningView.swift
Verifier/Screens/Check/VerifyScannerViewController.swift

This PR changes the behaviour of the torch for the verifier app: If turned on during scanning, the torch now stays on while the user is in the verification screen.
This was requested from people who use the app in dark surroundings and who would like to use the torch to look at the identification card (ID) or similar, after scanning the certificate.

Verifier: Keep torch on while in verification screen

---

Verifier/Logic/AppDelegate.swift
Wallet/Logic/AppDelegate.swift

Since the "currentNodes" of the SDK is also used in the UIState, the SDK needs to be initialized at the start such that any change to the UIState will not trigger a crash of the instancePrecondition() in the SDK.
E.g. on a clean install the wallet app deletes all certificates, this triggers a state update.

Fixes initialization of sdk

---

CovidCertificate/SharedLogic/Verifier/Verifier.swift

Don't propagate the error codes of modes errors as they provide too much information.

Remove mode error codes

---

CovidCertificate/SharedLogic/Verifier/Verifier.swift

to show correct message and allow retry (instead of showing "revoked" even if it's not on the revocation list)

Fix error handling of revocation verification 

---

Wallet/Screens/Certificates/WalletDetailViewController.swift
Wallet/Screens/Homescreen/HomescreenCertificatesViewController.swift

After a transfer-code expired (30+3 days currently), the app doesn't make any new requests to the backend (they are deleted in the DB anyways)

Only Refresh Transfercode if not expired

---

CovidCertificate/SharedLogic/Verifier/Verifier.swift
Verifier/Screens/Check/VerifyCheckContentViewController.swift
Verifier/Screens/Check/VerifyCheckViewController.swift

- Fixes info text in 2G+ success case
- Fixes wrong initialization of isError for invalid cases
- Check the first error, not the national error only

2G+ check fixes

---

Wallet/Logic/AppDelegate.swift

- fixes the order in which the SDK gets initialized on the first app start
- the wrong order of initialization can lead to a incomplete revocation list

Bugfix: Sdk initialization order

---

CovidCertificate/SharedLogic/Helpers/EuHealthCert+CC.swift
Wallet/Screens/Certificates/CertificateDetailView.swift
Wallet/Screens/Certificates/CertificateDetailViewController.swift
Wallet/Screens/Homescreen/HomescreenCertificateView.swift

this resolved issue #247
Android Implementation: https://github.com/admin-ch/CovidCertificate-SDK-Kotlin/blob/7b491f1b37f6f95f4ae63d3144f3c960738ff809/src/main/java/ch/admin/bag/covidcertificate/sdk/core/extensions/VaccinationEntryExtensions.kt#L36-L38

fixes the vaccination label for certificates where doseNumber is greater than totalDoses

---

CovidCertificate.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

that includes the pre-packaged revocation list (https://github.com/admin-ch/CovidCertificate-SDK-iOS/pull/129)

Update SDK 

---

CovidCertificate/SharedLogic/Verifier/Verifier.swift
Verifier/Screens/Check/VerifyCheckContentViewController.swift
Wallet/Screens/Certificates/Abroad/CertificateCheckAbroadVerificationStateView.swift
Wallet/Screens/Certificates/CertificateDetailViewController.swift
Wallet/Screens/Certificates/CertificateStateView.swift

Also propagate ch-only property for invalid certificate s.t. they can be identified. These certificates should not show the foreign check button on the detail.

Don't allow ch-certificates to show foreign check button if invalid
