admin-ch/CovidCertificate-App-iOS

- CovidCertificate/Supporting Files/Impressum/de/impressum.html
- CovidCertificate/Supporting Files/Impressum/en/impressum.html
- CovidCertificate/Supporting Files/Impressum/fr/impressum.html
- CovidCertificate/Supporting Files/Impressum/it/impressum.html
- Fixes telephone number
- Fixes URL
> updates imprint

- CovidCertificate/SharedUI/Views/QRCodeNameView.swift
- Wallet/Screens/Homescreen/HomescreenCertificateView.swift
- Wallet/Screens/Homescreen/HomescreenCertificatesViewController.swift
Applies meaningful autolayout content priorities to display certificates better on homescreen of small phones.
> improves display of certificates for small phones

- CovidCertificate.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> updates covid certificate sdk

- CovidCertificate.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- CovidCertificate/Supporting Files/Impressum/en/licence.html
- CovidCertificate/Supporting Files/Impressum/fr/licence.html
- CovidCertificate/Supporting Files/Impressum/it/licence.html
- Translations/Strings+Generated.swift
- Translations/fr.lproj/Localizable.strings
- Translations/it.lproj/Localizable.strings
- Wallet/Screens/Homescreen/WalletHomescreenViewController.swift
- Updates translations and imprint
- Simple UI bugfixes
- Fixes logic of certificate validity in SDK
> Release Candidate

- README.md
Add missing hyperlinks to the README.
> Add missing hyperlinks

- CovidCertificate/SharedUI/Views/InfoBoxView.swift
Improve UX by also allowing not only to press close button, but also tap the background.
> allows to close the infoboxes on background view tap

- CovidCertificate.xcodeproj/project.pbxproj
- updates marketing version number for wallet and verifier to 1.1.0
> updates marketing version for verifier & wallet

- CovidCertificate/SharedUI/Views/QRScanner/NSQRScanningView.swift
Only reinitialize AVCaptureSession if it's needed to avoid second initialization when scanner is started after selecting OK on the camera permission alert for the user.
> fixes re-initialization of camera layer in scanner

- Translations/Strings+Generated.swift
- Translations/de.lproj/Localizable.strings
- Translations/en.lproj/Localizable.strings
- Translations/fr.lproj/Localizable.strings
- Translations/it.lproj/Localizable.strings
- Wallet/Screens/Certificates/CertificateDetailView.swift
This PR updates translations (+ swiftformat)
> Translations

- CovidCertificate.xcodeproj/project.pbxproj
- CovidCertificate/Supporting Files/Wallet-Info.plist
- Wallet/Logic/AppDelegate.swift
- Wallet/Logic/ImportHandler/ImportHandler.swift
- Wallet/Logic/User/WalletUserStorage.swift
- Wallet/Screens/Certificates/CertificateAddDetailViewController.swift
- Wallet/Screens/Certificates/WalletScannerViewController.swift
- Adds ability to import Covid certificates via share as pictures or PDF files
- Shows basic error popup if no picture could be scanned or no QR Code could be found on the image
> Basic PDF & Image Import Feature

- CovidCertificate.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> Updates SDK

- CovidCertificate.xcodeproj/project.pbxproj
- CovidCertificate/Resources/Config/config_check.json
- CovidCertificate/Resources/Config/config_wallet.json
- Translations/Strings+Generated.swift
- Translations/de.lproj/Localizable.strings
- Translations/en.lproj/Localizable.strings
- Translations/fr.lproj/Localizable.strings
- Translations/it.lproj/Localizable.strings
- Translations/rm.lproj/InfoPlist.strings
- Translations/rm.lproj/Localizable.strings
- adds rumantsch
- updates local config files
- changes development language to "en"
> Adds Rumantsch as language

- CovidCertificate.xcodeproj/project.pbxproj
- CovidCertificate.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- CovidCertificate/SharedLogic/Verifier/Verifier.swift
- Wallet/Screens/Certificates/CertificateDetailViewController.swift
- uses forceUpdate correctly for Verifier()
> Feature: Adds Force Reload to Wallet Certificate Detail

- CovidCertificate.xcodeproj/project.pbxproj
- CovidCertificate.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- CovidCertificate/SharedLogic/Networking/Config/Environment.swift
- Verifier/Logic/AppDelegate.swift
- Wallet/Logic/AppDelegate.swift
- adds app token to initialize CovidCertificate SDK
> Feature: App Token

- CovidCertificate.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- CovidCertificate/SharedLogic/Networking/Config/ConfigManager.swift
Include new CN pins
Update SDK to include new CN pins
> include new cn pins

- CovidCertificate/SharedUI/Base/StaticContent/StaticContentViewModel.swift
- CovidCertificate/SharedUI/Controls/SimpleTextButton.swift
- Translations/Strings+Generated.swift
- Translations/de.lproj/Localizable.strings
- Translations/en.lproj/Localizable.strings
- Translations/fr.lproj/Localizable.strings
- Translations/it.lproj/Localizable.strings
- Translations/rm.lproj/Localizable.strings
- adds button in "how to" of wallet scanner to reeceive further information
> Feature: Wallet Scanner How To Button for more information

- CovidCertificate.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- spm update to latest version of sdk
> Update to latest SDK

- CovidCertificate/SharedLogic/Networking/Config/ConfigManager.swift
This PR removes an old comment which is not true anymore
> Remove superfluous comment

- CovidCertificate.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Caches rules and value sets, such that it is deserialized once:
C.f. https://github.com/admin-ch/CovidCertificate-SDK-iOS/pull/37
> Improve performance during rule parsing

- CovidCertificate.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
This PR updates to the latest version of the SDK
> Update SDK to latest version

- Wallet/Logic/UIStateManager/UIStateManager.swift
> Fixes state update logic

- CovidCertificate.xcodeproj/project.pbxproj
- CovidCertificate/Supporting Files/Wallet-Info.plist
This pull-request bumps the version of the app to 1.2.0
> Bump version to 1.2.0

- CovidCertificate.xcodeproj/project.pbxproj
- Wallet/Logic/AppDelegate.swift
- Wallet/Logic/User/Migration.swift
- Wallet/Logic/User/SecureStorage/Enclave.swift
- Wallet/Logic/User/SecureStorage/SecureStorage.swift
- Wallet/Logic/User/WalletUserStorage.swift
- migration to secure storage in Wallet app
> Migration from Keychain to SecureStorage

- Wallet/Logic/UIStateManager/UIStateManager.swift
- Wallet/Screens/Homescreen/HomescreenBottomView.swift
This PR loads/refreshes certificates and their state asynchronously on DispatchQueue.global() to not block main (UI) thread
> Load/refresh certificates and their state asynchronously 

- CovidCertificate.xcodeproj/project.pbxproj
> Bump version number to 2.0

- Verifier/Screens/Check/VerifyCheckContentViewController.swift
- Verifier/Screens/Check/VerifyInfoView.swift
- Wallet/Screens/Onboarding/OnboardingBaseViewController.swift
- Improves accessibility handling of wallet onboarding
- Improves verification detail screen accessibility handling
> Voice-Over Improvements

- Translations/Strings+Generated.swift
- Translations/de.lproj/Localizable.strings
- Translations/en.lproj/Localizable.strings
- Translations/fr.lproj/Localizable.strings
- Translations/it.lproj/Localizable.strings
- Translations/rm.lproj/Localizable.strings
- Verifier/Screens/Check/VerifyCheckContentViewController.swift
- Wallet/Screens/Certificates/CertificateDetailView.swift
- Wallet/Screens/Certificates/CertificateDetailViewController.swift
- Wallet/Screens/Homescreen/HomescreenCertificateView.swift
display evidence instead of certificate if numberOfDoses != totalDoses
> Incomplete certificate

- Wallet/Logic/TransferCode/TransferManager.swift
- Wallet/Screens/Homescreen/PushNotificationPopupView.swift
- Wallet/Screens/Homescreen/WalletHomescreenViewController.swift
- Wallet/Screens/TransferCode/TransferCodeNextStepsViewController.swift
and move setActive to TransferManager in order to update it on app start
> Only set PushManager to active if permission was given

- CovidCertificate/SharedUI/Base/WebViewController.swift
- CovidCertificate/Supporting Files/Impressum/de/impressum.html
- CovidCertificate/Supporting Files/Impressum/en/impressum.html
- CovidCertificate/Supporting Files/Impressum/fr/impressum.html
- CovidCertificate/Supporting Files/Impressum/it/impressum.html
- CovidCertificate/Supporting Files/Impressum/rm/impressum.html
Send different app identifier as get parameter in imprint developer link 
Related: https://github.com/admin-ch/CovidCertificate-App-Android/pull/160
> Imprint Link App Identifier 

- Wallet/Logic/AppDelegate.swift
- Wallet/Screens/Onboarding/OnboardingViewController.swift
Delay WalletHomescreenViewController initialization until onboarding is completed
> Fixes initialization of Viewcontrollers in Onboarding

- Wallet/Screens/Certificates/CertificateDetailView.swift
- fixes country label for test and recovery in certificate detail
> Bugfix: Country label

- CovidCertificate.xcodeproj/project.pbxproj
- CovidCertificate.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- CovidCertificate/SharedLogic/Helpers/EuHealthCert+CC.swift
- CovidCertificate/SharedLogic/Verifier/Verifier.swift
- CovidCertificate/SharedUI/Views/QRCodeNameView.swift
- Translations/Strings+Generated.swift
- Translations/de.lproj/Localizable.strings
- Translations/en.lproj/Localizable.strings
- Translations/fr.lproj/Localizable.strings
- Translations/it.lproj/Localizable.strings
- Translations/rm.lproj/Localizable.strings
- Verifier/Screens/Check/VerifyCheckContentViewController.swift
- Verifier/Screens/Check/VerifyCheckViewController.swift
- Verifier/Screens/Check/VerifyScannerViewController.swift
- Wallet/Screens/Certificates/CertificateAddDetailView.swift
- Wallet/Screens/Certificates/CertificateDetailView.swift
- Wallet/Screens/Certificates/CertificateDetailViewController.swift
- Wallet/Screens/Certificates/CertificateStateView.swift
- Wallet/Screens/Certificates/CertificateTableViewCell.swift
- Wallet/Screens/Homescreen/HomescreenCertificateView.swift
- updates CovidCertificate SDK to latest main version
> Feature: update SDK to latest version

- CovidCertificate.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Wallet/Logic/Transformation/TransformationPayload.swift
- Wallet/Logic/Transformation/TransformationService.swift
- renames qrcode to qrCode
- update SDK to latest version
> minor light certificate adjustments

- Wallet/Logic/TransferCode/TransferManager.swift
- Wallet/Logic/User/WalletUserStorage.swift
- make sure the sam QrCode is not added twice
- for in-app delivery store pdf for all certificates
> Bugfix: inApp delivery duplicate certificate

- CovidCertificate.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- CovidCertificate/Resources/Config/config_check.json
- CovidCertificate/Resources/Config/config_wallet.json
- CovidCertificate/SharedLogic/Verifier/Verifier.swift
- Translations/Strings+Generated.swift
- Translations/de.lproj/Localizable.strings
- Translations/en.lproj/Localizable.strings
- Translations/fr.lproj/Localizable.strings
- Translations/it.lproj/Localizable.strings
- Translations/rm.lproj/Localizable.strings
- Verifier/Screens/Check/VerifyCheckContentViewController.swift
- Wallet/Screens/Certificates/CertificateStateView.swift
- Wallet/Screens/Certificates/CertificateTableViewCell.swift
- Hide revocation check if check was skipped
- update translations
- update local config files
> Hide revocation check if check was skipped

- Wallet/Logic/Transformation/TransformationManager.swift
- Wallet/Screens/Certificates/CertificateDetailViewController.swift
- show export detail even if pdf is already loaded for consistency
> Bugfix: show export detail even if pdf is already loaded

- CovidCertificate.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Wallet/Screens/TransferCode/TransferCodeLabel.swift
- adds menu to copy transfercode to clipboard
> Copy transfercode to clipboard

- CovidCertificate.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Wallet/Logic/AppDelegate.swift
- Wallet/Logic/ImportHandler/ImportHandler.swift
Don't store navigationcontroller in pdf import. This is issue because the rootviewcontroller is initially the onboarding viewcontroller.
> Fixes PDF import after first installation

- CovidCertificate.xcodeproj/project.pbxproj
- Translations/Strings+Generated.swift
- Translations/de.lproj/Localizable.strings
- Translations/en.lproj/Localizable.strings
- Translations/fr.lproj/Localizable.strings
- Translations/it.lproj/Localizable.strings
- Translations/rm.lproj/Localizable.strings
> Version 2.2.0

- CovidCertificate.xcodeproj/project.pbxproj
- CovidCertificateTests/UIStateManagerTests.swift
- Wallet/Logic/UIStateManager/UIStateManager.swift
UIStateManager was accessing its properties on multiple threads which could result in a crash.
> Bugfix: UIStateManager threading

- Translations/Strings+Generated.swift
- Translations/de.lproj/Localizable.strings
- Translations/en.lproj/Localizable.strings
- Translations/fr.lproj/Localizable.strings
- Translations/it.lproj/Localizable.strings
- Translations/rm.lproj/Localizable.strings
- Wallet/Logic/Transformation/TransformationError.swift
- Wallet/Logic/Transformation/TransformationManager.swift
- Wallet/Logic/Transformation/TransformationService.swift
adds error message for transformation service rate limiting
> Rate limiting error message

- Wallet/Logic/TransferCode/TransferManager.swift
cachedResult cachedLastLoad was written to from multiple threads simultaneously which can cause crashes
> Resolves threading issue in transfermanager

- CovidCertificate.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
This pull-request updates the SwiftCBOR dependency
> Update SwiftCBOR dependency

- CovidCertificate.xcodeproj/project.pbxproj
- CovidCertificate/SharedUI/Base/CopyAbleLabelOverlay.swift
- Wallet/Screens/Certificates/CertificateDetailView.swift
- Wallet/Screens/TransferCode/TransferCodeLabel.swift
Add a copy overlay for UVCI value in the detail of a certificate.
> Adds copy functionality in detail view for UVCI value

- Translations/Strings+Generated.swift
- Translations/de.lproj/Localizable.strings
- Translations/en.lproj/Localizable.strings
- Translations/fr.lproj/Localizable.strings
- Translations/it.lproj/Localizable.strings
- Translations/rm.lproj/Localizable.strings
- Wallet/Logic/TransferCode/InAppDelivery.swift
- Wallet/Logic/TransferCode/TransferError.swift
- Wallet/Screens/TransferCode/TransferCodeErrorView.swift
In case that the user changes his phone time, a special error code is provided by the backend. We use these to provide a better error to the user.
> Optimize Transfer-Code network errors

- Translations/Strings+Generated.swift
- Translations/de.lproj/Localizable.strings
- Translations/en.lproj/Localizable.strings
- Translations/fr.lproj/Localizable.strings
- Translations/it.lproj/Localizable.strings
- Translations/rm.lproj/Localizable.strings
- Wallet/Logic/User/Migration.swift
- Wallet/Logic/User/SecureStorage/Enclave.swift
- Wallet/Logic/User/SecureStorage/SecureStorage.swift
- Wallet/Logic/User/WalletUserStorage.swift
- Wallet/Screens/Homescreen/WalletHomescreenViewController.swift
Adds an error popup for the case when certificates can not be decrypted. This should never happen, but if it would we will at least get an error code to find the issue.
> Decryption errorpopup

- Wallet/Logic/AppDelegate.swift
- fixes ordering in app delegate
> Delete keys after deleting certificates

- Wallet/Logic/User/UserTransferCode.swift
Fixes minor bug for transfer code duration image on transfer code status view.
> Flip image order for transfer code

- CovidCertificate.xcodeproj/project.pbxproj
- CovidCertificate.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- CovidCertificate/SharedLogic/Networking/Config/ConfigManager.swift
- CovidCertificate/SharedLogic/Networking/Config/ConfigResponseBody.swift
- CovidCertificate/SharedLogic/Networking/Config/SDKOptionsManager.swift
- Verifier/Logic/AppDelegate.swift
- Wallet/Logic/AppDelegate.swift
This PR reads a feature flag from the config request, which allows to enable/disable timeshift detection from the backend
> Load feature flag (timeshiftDetectionEnabled) from backend 

- CovidCertificate.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- CovidCertificate/SharedLogic/Verifier/Verifier.swift
> Allow empty mode and update sdk

- CovidCertificate/SharedUI/Views/IconTextInfoBoxView.swift
- Wallet/Screens/Certificates/CertificateDetailViewController.swift
- Wallet/Screens/Certificates/CertificateModesView.swift
Use less height to improve space on smaller devices.
> Improves images in mode info box

- Wallet/Screens/Certificates/CertificateTableViewCell.swift
Show correct immunisation type for antibody test as in certificate detail.
> Fixes antibody test type in CertificateTableViewCell

- CovidCertificate/SharedUI/Views/ScanModeButton.swift
- Verifier/Screens/Homescreen/VerifierHomescreenViewController.swift
- add inset for main button on homescreen
- less contentPriority for scan mode button
> Fixes scan mode button for small phones

- Verifier/Screens/Check/VerifyCheckViewController.swift
- if started offline no mode is set, also start retry with no mode
> Start retry also without mode set

- Wallet/Screens/Certificates/WalletDetailViewController.swift
- Wallet/Screens/Homescreen/HomescreenCertificatesViewController.swift
This reverts commit 8c97078e65ecfd09b46a5637615aa838772cab4e.
> Revert "only refresh transfercode if it's valid, don't refresh if expired"

- CovidCertificate/Resources/Config/config_check.json
- CovidCertificate/Resources/Config/config_wallet.json
This PR updates the pre-packaged config.
> Update pre-packaged fallback config

- Wallet/Screens/Certificates/WalletScannerViewController.swift
This fixes the problem when the rescan is faster than the animation that lead to an empty screen.
> Fixes problem with empty screens after rescan

- CovidCertificate.xcodeproj/project.pbxproj
- CovidCertificate.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Translations/Strings+Generated.swift
- Translations/de.lproj/Localizable.strings
- Translations/en.lproj/Localizable.strings
- Translations/fr.lproj/Localizable.strings
- Translations/it.lproj/Localizable.strings
- Translations/rm.lproj/Localizable.strings
- Wallet/Screens/Certificates/CertificateDetailView.swift
- Wallet/Screens/Certificates/CertificateDetailViewController.swift
- Wallet/Screens/Certificates/CertificateNoteView.swift
- iosTranslation.json
- only show target disease, start of validity, issuing office and issued-in-information
> Adds detail view for medical exemption certificate

- CovidCertificate/SharedLogic/Networking/Config/ConfigResponseBody.swift
- Wallet/Screens/Certificates/RefreshInfoPopupView.swift
- make new config values optional
> Fixes decoding of old config

- CovidCertificate/Resources/Config/config_check.json
- CovidCertificate/Resources/Config/config_wallet.json
> Config update

- Translations/de.lproj/Localizable.strings
- Translations/en.lproj/Localizable.strings
- Translations/fr.lproj/Localizable.strings
- Translations/it.lproj/Localizable.strings
- Translations/rm.lproj/Localizable.strings
- iosTranslation.json
- updates project ID
- updates translations
> update poeditor project to BIT project

- Wallet/Screens/Homescreen/HomescreenCertificateView.swift
- Wallet/Screens/TransferCode/TransferCodeDetailViewController.swift
- fixes two views where transfer code update is started also in failed state
> Only start transfer code request when not already in failed state

- CovidCertificate/SharedUI/Base/StaticContent/OnboardingInfoView.swift
- CovidCertificate/SharedUI/Views/IconImageRowView.swift
- CovidCertificate/SharedUI/Views/IconTextInfoBoxView.swift
- Wallet/Screens/Certificates/CertificateModesView.swift
- Improves buttons at bottom of certificate detail
- Improves info button for modes on certificate detail
> Accessibility improvements

- Wallet/Screens/Homescreen/HomescreenEOLBannerView.swift
- limit HomescreenEOLBannerView title to one line
> HomescreenEOLBannerView title fix

- CovidCertificate.xcodeproj/project.pbxproj
- CovidCertificate.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Translations/Strings+Generated.swift
- Translations/de.lproj/Localizable.strings
- Translations/en.lproj/Localizable.strings
- Translations/fr.lproj/Localizable.strings
- Translations/it.lproj/Localizable.strings
- Translations/rm.lproj/Localizable.strings
- Wallet/Screens/Certificates/CertificateDetailView.swift
- Wallet/Screens/Certificates/CertificateDetailViewController.swift
- Wallet/Screens/Certificates/CertificateNoteView.swift
- Wallet/Screens/Certificates/CertificateTableViewCell.swift
- shows positive rat tests as recovery
> Positive rat tests as recovery

- Wallet/Screens/Certificates/CertificateTableViewCell.swift
> Fixes test label for normal tests

- CovidCertificate/Resources/Config/config_wallet.json
- Translations/Strings+Generated.swift
- Translations/de.lproj/Localizable.strings
> Updates translations / config

- Wallet/Screens/Certificates/CertificateTableViewCell.swift
> Fixes state problem with cell reuse in certificate list

- CovidCertificate.xcodeproj/project.pbxproj
- CovidCertificate/Resources/Config/config_wallet.json
- adds target which updates both config files
- update the configs
> Feature: update configs

- CovidCertificate.xcodeproj/project.pbxproj
- CovidCertificate/SharedLogic/Networking/Base/Backend.swift
- CovidCertificate/SharedLogic/Networking/Base/UBPinnedCertificatesTrustEvaluator.swift
- CovidCertificate/SharedUI/Base/StaticContent/StaticContentViewController.swift
- CovidCertificate/SharedUI/Base/StaticContent/StaticContentViewModel.swift
- CovidCertificate/SharedUI/Helpers/ImageHelper/UIImage+CC.swift
- CovidCertificate/SharedUI/Views/QRScanner/NSQRScanningView.swift
- Translations/Strings+Generated.swift
- Translations/de.lproj/Localizable.strings
- Translations/en.lproj/Localizable.strings
- Translations/fr.lproj/Localizable.strings
- Translations/it.lproj/Localizable.strings
- Translations/rm.lproj/Localizable.strings
- Verifier/Logic/AppDelegate.swift
- Wallet/Logic/AppDelegate.swift
Fix accessibilityLabels on InfoIcons
> AX: Fix accessibility issues

- CovidCertificate.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- CovidCertificate/SharedLogic/Verifier/Verifier.swift
- Wallet/Logic/Error/WalletErrors+CC.swift
- Wallet/Screens/Certificates/Abroad/CertificateCheckAbroadVerificationStateView.swift
- Wallet/Screens/Certificates/CertificateDetailViewController.swift
- Wallet/Screens/Certificates/CertificateStateView.swift
- Wallet/Screens/Certificates/CertificateTableViewCell.swift
- Wallet/Screens/Homescreen/HomescreenCertificateView.swift
> fixes signature expired certificates

- CovidCertificate/SharedUI/Controls/LeadingTrailingIconButton.swift
- CovidCertificate/SharedUI/Controls/SimpleTextButton.swift
- Wallet/Screens/Certificates/RatConversion/RatConversionDetailViewController.swift
- Fixed die Grösse des "Zum Formular" Button
- Fixed die External Link Buttons
- Fixed den Reise-Button (LeadingTrailingIconButton
)
> Button Grössen Probleme

- .github/workflows/build.yml
- .github/workflows/codequality.yml
> Use Xcode 13.3.1

- CovidCertificate.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
This reverts commit 6f72be6f073c743aab53fde903154589ffd3be04.
> Revert "updates sdk"

- CovidCertificate.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- CovidCertificate/SharedUI/Helpers/QRCodeUtils.swift
- CovidCertificate/SharedUI/Helpers/UIImageView+CC.swift
- CovidCertificate/SharedUI/Views/QRCodeNameView.swift
- Wallet/Logic/Error/WalletErrors+CC.swift
- Wallet/Logic/TransferCode/TransferManager.swift
- Wallet/Logic/User/QRCodeImageCache.swift
- Wallet/Screens/Homescreen/HomescreenCertificatesViewController.swift
> Startup optimizations

- CovidCertificate/SharedUI/Controls/LeadingTrailingIconButton.swift
> fixes leading trailing icon button
